<?php
$siteName = 'Movie Recommendation System';
$adminEmail = 'adi@gmail.com';
$adminPassword = '123';
$defaultCategories = ['Sci-Fi', 'Horror', 'Thriller', 'Romantic', 'Fantasy', 'Action', 'Adventure', 'Drama', 'Mystery', 'Animation'];
$defaultMovies = [
    [
        'title' => 'Interstellar Voyage',
        'category' => 'Sci-Fi',
        'description' => 'A gravity-bending mission beyond Saturn leads a crew into a shimmering wormhole where memory, love, and time collide.',
        'poster_url' => 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=1200&q=80',
        'backdrop_url' => 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1400&q=80',
        'teaser_url' => 'https://www.youtube.com/embed/zSWdZVtXT7E?si=movie001',
        'release_year' => 2014,
        'rating' => '8.9',
        'duration' => '2h 49m',
    ],
    [
        'title' => 'Midnight Manor',
        'category' => 'Horror',
        'description' => 'When a podcast crew enters a cursed mansion, every whisper in the hallways becomes a terrifying clue about their fate.',
        'poster_url' => 'https://images.unsplash.com/photo-1509347528160-9a9e33742cdb?auto=format&fit=crop&w=1200&q=80',
        'backdrop_url' => 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1400&q=80',
        'teaser_url' => 'https://www.youtube.com/embed/sv1dNckq2LY?si=movie002',
        'release_year' => 2022,
        'rating' => '8.1',
        'duration' => '1h 58m',
    ],
    [
        'title' => 'Velvet Signals',
        'category' => 'Romantic',
        'description' => 'Two radio hosts with hidden identities fall in love through midnight letters and songs that keep crossing their frequencies.',
        'poster_url' => 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=1200&q=80',
        'backdrop_url' => 'https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?auto=format&fit=crop&w=1400&q=80',
        'teaser_url' => 'https://www.youtube.com/embed/3s1rvMFUweQ?si=movie003',
        'release_year' => 2023,
        'rating' => '7.8',
        'duration' => '2h 02m',
    ],
    [
        'title' => 'Shadow Frequency',
        'category' => 'Thriller',
        'description' => 'A cyber analyst hunts a ghost network whose voice messages predict crimes before they unfold across the city.',
        'poster_url' => 'https://images.unsplash.com/photo-1513106580091-1d82408b8cd6?auto=format&fit=crop&w=1200&q=80',
        'backdrop_url' => 'https://images.unsplash.com/photo-1496307042754-b4aa456c4a2d?auto=format&fit=crop&w=1400&q=80',
        'teaser_url' => 'https://www.youtube.com/embed/vKQi3bBA1y8?si=movie004',
        'release_year' => 2024,
        'rating' => '8.4',
        'duration' => '2h 10m',
    ],
    [
        'title' => 'Starlight Rebellion',
        'category' => 'Action',
        'description' => 'A rogue pilot and a royal engineer ignite a rebellion above neon planets, racing to steal a weaponized sun core.',
        'poster_url' => 'https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=1200&q=80',
        'backdrop_url' => 'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?auto=format&fit=crop&w=1400&q=80',
        'teaser_url' => 'https://www.youtube.com/embed/5PSNL1qE6VY?si=movie005',
        'release_year' => 2021,
        'rating' => '8.6',
        'duration' => '2h 18m',
    ],
    [
        'title' => 'Dream Atlas',
        'category' => 'Fantasy',
        'description' => 'An apprentice cartographer maps a realm hidden inside dreams and unlocks gateways painted in moonlit violet.',
        'poster_url' => 'https://images.unsplash.com/photo-1505685296765-3a2736de412f?auto=format&fit=crop&w=1200&q=80',
        'backdrop_url' => 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1400&q=80',
        'teaser_url' => 'https://www.youtube.com/embed/eOrNdBpGMv8?si=movie006',
        'release_year' => 2020,
        'rating' => '7.9',
        'duration' => '2h 05m',
    ],
    [
        'title' => 'Neon Abyss',
        'category' => 'Sci-Fi',
        'description' => 'Deep-sea explorers discover a bioluminescent intelligence under the Pacific that can rewrite the future.',
        'poster_url' => 'https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=1200&q=80',
        'backdrop_url' => 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1400&q=80',
        'teaser_url' => 'https://www.youtube.com/embed/udDclJoHfE0?si=movie007',
        'release_year' => 2019,
        'rating' => '8.2',
        'duration' => '2h 11m',
    ],
    [
        'title' => 'Crimson Echoes',
        'category' => 'Mystery',
        'description' => 'A violin prodigy unravels an old concert hall murder through hidden notes, secret passages, and a haunted symphony.',
        'poster_url' => 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?auto=format&fit=crop&w=1200&q=80',
        'backdrop_url' => 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=1400&q=80',
        'teaser_url' => 'https://www.youtube.com/embed/EXeTwQWrcwY?si=movie008',
        'release_year' => 2022,
        'rating' => '7.7',
        'duration' => '1h 52m',
    ],
];
